### ISSUE TITLE
Add "slide" attack for player

### ISSUE THREAD

**Issue by Jigoku** [Jigoku/boxclip#98]
For the recently added player sprite, there is a single frame called "slide".
Possibly add this as an attack method.

For example, pressing a key whilst running, will perform a slide... this takes out enemies.

**Comment by rufio72** [comment]
I made the change and I would like to do the push, but I don't have the permissions. The new branch will be called: playerSlide.

**Comment by Jigoku** [comment]
Fixed in #103
